document.write("<p>");
document.write("Curso actual: ");
document.write(asignatura.curso);
document.write("</p>");
document.write("<p>");
document.write("Alumno: ");
document.write(asignatura.alumno);
document.write("</p>");
document.write("<p>");
document.write("E-mail: ");
document.write(asignatura.email);
document.write("</p>");